### ISSUE TITLE
[QA ver1.0] 지원하기 todo

### ISSUE THREAD

**Issue by limgahyun** [kahluaband/Homepage_FE_release#5]
지원하기
- [x] 글씨 밀림 현상
- [x] 아이패드 세로 화면 깨짐 현상
- [x] 날짜 오타 (모집일정 03.015)
- [x] 오타 및 띄어쓰기 확인
- [x] width 1080 이상에서 우측 여백
- [x] height 조정

지원폼
- [x] 지원폼 지원방법/입력칸 한줄에 두개 있도록
- [x] 신디 선택 시 400에러
- [x] 주의사항을 마지막에 체크한 경우 제출하기 버튼 비활성화
- [x] 오타 및 띄어쓰기 확인

지원 확인
- [x] 지원 확인 팝업창 레이아웃
- [x] 지원 확인 페이지 height
